name = "http-coach"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "history_storage"
id = "bc703c375edd44dc9b0e21f6fbfd8366"

[ai]
binding = "AI"
